- name: Publish package
  if: github.event_name == 'release' && github.event.action == 'published'
  uses: pypa/gh-action-pypi-publish@release/v1
  with:
    user: __token__
    password: ${{ secrets.PYPI_API_TOKEN }}
